app/views/main.py
# Created by carryon on 19-1-15.
from flask import Blueprint, render_template, request, flash, get_flashed_messages, redirect, current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import login_required

from app.models import Blog

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def index():
    # posts = Blog.query.filter_by().all()
    page = request.args.get('page', 1, type=int)
    pagination = Blog.query.filter_by().order_by(Blog.add_time.desc()).paginate(page, per_page=5,
                                                                                error_out=False)
    posts = pagination.items
    return render_template('main/index.html', posts=posts, pagination=pagination)


app/views/posts.py
# Created by carryon on 19-1-15.
from flask import Blueprint, render_template, url_for, request, flash, get_flashed_messages, redirect, jsonify
from flask_login import login_required, current_user

from app.exts import db
from app.forms import BlogForm, CommentForm
from app.models import Blog, Comment, Blogcol

posts = Blueprint('posts', __name__)


@posts.route('/collect/', methods=['GET', 'POST'])
@login_required
def collect():
    uid = request.args.get("uid", "")
    bid = request.args.get("bid", "")
    # print(uid, bid)
    blogcol = Blogcol.query.filter_by(
        user_id=int(uid),
        blog_id=int(bid)
    ).first()
    if blogcol:
        db.session.delete(blogcol)
        db.session.commit()
        data = dict(ok=0)
    else:
        blogcol = Blogcol(user_id=int(uid), blog_id=int(bid))
        db.session.add(blogcol)
        db.session.commit()
        data = dict(ok=1)
    return jsonify(data)


@posts.route('/search/', methods=['GET', 'POST'])
def search():
    some = request.args.get('some')
    print(some)
    page = request.args.get('page', 1, type=int)
    pagination = Blog.query.filter(Blog.text.contains(some)).order_by(Blog.add_time.desc()).paginate(page, per_page=5,
                                                                                                     error_out=False)
    posts = pagination.items
    return render_template('posts/search.html', posts=posts, pagination=pagination)


@posts.route('/write/', methods=['GET', 'POST'])
@login_required
def write():
    form = BlogForm()
    if form.validate_on_submit():
        user = current_user._get_current_object()
        p = Blog(title=form.title.data, text=form.text.data, user=user)
        db.session.add(p)
        return redirect(url_for('main.index'))
    return render_template('posts/write.html', form=form)


@posts.route('/index/', methods=['GET', 'POST'])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Blog.query.filter(Blog.uid == current_user.id).order_by(Blog.add_time.desc()).paginate(page,
                                                                                                        per_page=5,
                                                                                                        error_out=False)
    posts = pagination.items
    return render_template('posts/index.html', posts=posts, pagination=pagination)


@posts.route('/single/<_id_>', methods=['GET', 'POST'])
def single(_id_):
    form = CommentForm()
    if form.validate_on_submit():
        comm = Comment(content=form.text.data, user_id=current_user.id, blog_id=_id_)
        blog = Blog.query.filter(Blog.id == _id_).first()
        blog.commentnum += 1
        db.session.add(blog)
        db.session.add(comm)
        return redirect(url_for('posts.single', _id_=_id_))
    post = Blog.query.filter(Blog.id == _id_).first()
    comments = Comment.query.filter(Comment.blog_id == _id_).all()
    return render_template('posts/single.html', post=post, form=form, comments=comments)


app/views/users.py
# Created by carryon on 19-1-15.
import os

from PIL import Image
from flask import Blueprint, render_template, url_for, request, flash, get_flashed_messages, redirect, make_response, \
    session, current_app
from io import BytesIO
from app.forms import RegisterForm, LoginForm, UploadForm, ChpwForm, PwrtquetForm, PwrtForm
from app.models import User, Comment, Blogcol
from app.exts import db, photos
from app.email import send_mail
from app import code
from flask_login import login_required, login_user, logout_user, current_user

users = Blueprint('users', __name__)


@users.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        if session.get('image') != form.verify_code.data:
            flash('验证码错误')
            return render_template('user/register.html', form=form)
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None:
            flash("用户名已被占用")
            return render_template('user/register.html', form=form)

        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            flash("邮箱已被注册过，不能重复注册")
            return render_template('user/register.html', form=form)

        u = User(username=form.username.data, password=form.password.data, email=form.email.data)
        db.session.add(u)
        db.session.commit()

        # 生成token  用u对象调用模型中的方法
        token = u.generate_active_token()
        send_mail(u.email, '账户激活', 'email/activate', username=u.username, token=token)
        flash("恭喜注册成功,请点击邮件中的链接完成激活")
        return redirect(url_for('users.login'))
    return render_template('user/register.html', form=form)


# 这个方法用来验证token  给用户邮箱发送过去一个完整的url
@users.route('/active/<token>', methods=['GET', 'POST'])
def active(token):
    if User.check_active_token(token):
        flash("账户激活成功")
        return redirect(url_for('users.login'))
    else:
        flash("账户激活失败")
        return redirect(url_for('main.index'))


@users.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        if session.get('image') != form.verify_code.data:
            flash('验证码错误')
            return render_template('user/login.html', form=form)

        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.verify_password(form.password.data):
            # flash('验证通过，登录成功')
            login_user(user, remember=form.remember.data)
            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash('用户名或者密码不正确')
            return render_template('user/login.html', form=form)

    return render_template('user/login.html', form=form)


@users.route('/getcode/')
def getcode():
    image, str = code.validate_picture()
    # 将验证码图片以二进制形式写入在内存中，防止将图片都放在文件夹中，占用大量磁盘
    buf = BytesIO()
    image.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    # 把二进制作为response发回前端，并设置首部字段
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/gif'
    # 将验证码字符串储存在session中
    session['image'] = str
    return response


@users.route('/logout/', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash("退出登录成功")
    return redirect(url_for('main.index'))


@users.route('/changeimg/', methods=['GET', 'POST'])
@login_required
def changeimg():
    img_url = ''
    form = UploadForm()
    if form.validate_on_submit():
        # 获取文件后缀
        suffix = os.path.splitext(form.icon.data.filename)[1]
        # 随机文件名  拼接
        filename = random_string() + suffix
        photos.save(form.icon.data, name=filename)
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], filename)
        img = Image.open(pathname)
        img.thumbnail((128, 128))
        img.save(pathname)
        if current_user.icon != 'default.jpg':
            path = current_app.config['UPLOADED_PHOTOS_DEST'] + current_user.icon
            os.remove(path)
        current_user.icon = filename  # 将新上传的文件名 赋值给 用户的头像
        db.session.add(current_user)  # 保存在数据库中
        flash("头像上传成功")
        return redirect(url_for("users.changeimg"))
    img_url = photos.url(current_user.icon)
    return render_template('user/changeimg.html', form=form, img_url=img_url)


def random_string(length=10):
    import random
    base_str = 'abc123defhijklmnopqrstuvwxyz4567890'
    return ''.join(random.choice(base_str) for i in range(length))


# 个人中心 待补充
@users.route('/index/', methods=['GET', 'POST'])
def index():
    return render_template('user/index.html')


@users.route('/change_pw/', methods=['GET', 'POST'])
@login_required
def change_pw():
    form = ChpwForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.oldpassword.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            db.session.commit()
            flash("密码修改成功")
            logout_user()
            return redirect(url_for('users.login'))
        else:
            flash("密码错误")
            return redirect(url_for('users.change_pw'))
    return render_template('user/change_pw.html', form=form)


@users.route('/reset_pw/', methods=['GET', 'POST'])
def password_request():
    form = PwrtquetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            token = user.generate_active_token()
            send_mail(user.email, '重置密码', 'email/resetpw', username=user.username, token=token)
            flash("邮件已发送,点击邮件的链接完成密码重置")
            return redirect(url_for('users.login'))
        else:
            flash("没有用户注册过这个邮箱！")
            return redirect(url_for('users.login'))
    return render_template('user/reset_pw.html', form=form)


@users.route('/reset/<token>', methods=['GET', 'POST'])
def reset(token):
    form = PwrtForm()
    if form.validate_on_submit():
        if User.check_reset_token(token, form.password.data):
            flash("密码重置成功")
            return redirect(url_for('users.login'))
        else:
            flash("密码重置失败")
            return redirect(url_for('users.login'))
    return render_template('user/change_pw.html', form=form)


@users.route('/collect/')
def collect():
    page = request.args.get('page', 1, type=int)
    pagination = Blogcol.query.filter(Blogcol.user_id == current_user.id).order_by(Blogcol.add_time.desc()).paginate(page,
                                                                                                        per_page=5,
                                                                                                        error_out=False)
    posts = pagination.items
    return render_template('user/collect.html', posts=posts, pagination=pagination)

app/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{#定制标题#}
{% block title %}
    默认标题
{% endblock %}

{#定制导航条#}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">首页</a>

            </div>
            <form class="navbar-form navbar-left" action="{{ url_for('posts.search') }}" method="get">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" name="some">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            {% if current_user.is_authenticated %}
                <a class="navbar-brand" href="{{ url_for('posts.index') }}">我的博客</a>
                <a class="navbar-brand" href="{{ url_for('posts.write') }}">写博客</a>
            {% endif %}
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#">{{ current_user.username }}</a></li>
                            <li><a href="{{ url_for('users.logout') }}">退出</a></li>
                        </ul>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">选项 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('users.changeimg') }}">修改头像</a></li>
                                <li><a href="{{ url_for('users.change_pw') }}">修改密码</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for("users.collect") }}">我的收藏</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for("users.login") }}">登录</a></li>
                        <li><a href="{{ url_for("users.register") }}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

{% endblock %}

{#定制内容 #}
{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}

        {% block page_content %}
            默认内容
        {% endblock %}
    </div>


    <footer>
        {% block footer %}
            <footer class="blog-footer">
                <hr>
                <p align="center">@2019 | Blog template built for <a href="http://www.cnblogs.com/zllwxm123">carryon</a>
                </p>
                <p align="center">
                    <a href="#">Back to top</a>
                </p>
            </footer>
        {% endblock %}
    </footer>
{% endblock %}



{#定制脚本#}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

app/templates/common/error.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
    默认标题
{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container" align="center">
            {% block page_content %}

            {% endblock %}
            <p><a class="btn btn-primary btn-lg" href="{{ url_for('main.index') }}" role="button">回到首页</a></p>
        </div>
    </div>
{% endblock %}

app/templates/common/macro.html
{#第一个参数 pagination对象 第二个 跳转到哪里去#}
{% macro pagination_show(pagination,endpoint) %}
<nav aria-label="Page navigation">
  <ul class="pagination">
{#      上一页#}
    <li {% if not pagination.has_prev %} class="disabled" {% else %} {% endif %}>
      <a href="{% if pagination.has_prev %}{{ url_for(endpoint,page=pagination.prev_num,**kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
{#      中间页码#}
    {% for p in pagination.iter_pages() %}
        {% if p %}
{#            www.baidu.com?page=#}
            <li {% if pagination.page == p  %} class="active" {% endif %}><a href="{{ url_for(endpoint,page=p,**kwargs) }}">{{ p }}</a></li>
        {% else %}
            <li><a href="#">&hellip;</a></li>
        {% endif %}

    {% endfor %}

{#      下一页#}
   <li {% if not pagination.has_next %} class="disabled" {% else %}{% endif %}>
      <a href="{% if pagination.has_next %}{{ url_for(endpoint,page=pagination.next_num,**kwargs) }}{% else %}#{% endif %}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

{% endmacro %}

app/templates/common/write.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}