app/forms/posts.py
# Created by carryon on 19-1-16.
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, EqualTo, Email
from wtforms.validators import ValidationError
from flask_wtf.file import FileField, FileRequired, FileAllowed


#写博客表单
class BlogForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired()])
    text = TextAreaField('正文', validators=[DataRequired()])
    submit = SubmitField('提交')


#评论表单
class CommentForm(FlaskForm):
    text = TextAreaField('say something:', validators=[DataRequired()])
    submit = SubmitField('评论')

app/views/posts.py
# Created by carryon on 19-1-15.
from flask import Blueprint, render_template, url_for, request, flash, get_flashed_messages, redirect, jsonify
from flask_login import login_required, current_user

from app.exts import db
from app.forms import BlogForm, CommentForm
from app.models import Blog, Comment, Blogcol

posts = Blueprint('posts', __name__)


@posts.route('/collect/', methods=['GET', 'POST'])
@login_required
def collect():
    uid = request.args.get("uid", "")
    bid = request.args.get("bid", "")
    # print(uid, bid)
    blogcol = Blogcol.query.filter_by(
        user_id=int(uid),
        blog_id=int(bid)
    ).first()
    if blogcol:
        db.session.delete(blogcol)
        db.session.commit()
        data = dict(ok=0)
    else:
        blogcol = Blogcol(user_id=int(uid), blog_id=int(bid))
        db.session.add(blogcol)
        db.session.commit()
        data = dict(ok=1)
    return jsonify(data)


@posts.route('/search/', methods=['GET', 'POST'])
def search():
    some = request.args.get('some')
    print(some)
    page = request.args.get('page', 1, type=int)
    pagination = Blog.query.filter(Blog.text.contains(some)).order_by(Blog.add_time.desc()).paginate(page, per_page=5,
                                                                                                     error_out=False)
    posts = pagination.items
    return render_template('posts/search.html', posts=posts, pagination=pagination)


@posts.route('/write/', methods=['GET', 'POST'])
@login_required
def write():
    form = BlogForm()
    if form.validate_on_submit():
        user = current_user._get_current_object()
        p = Blog(title=form.title.data, text=form.text.data, user=user)
        db.session.add(p)
        return redirect(url_for('main.index'))
    return render_template('posts/write.html', form=form)


@posts.route('/index/', methods=['GET', 'POST'])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Blog.query.filter(Blog.uid == current_user.id).order_by(Blog.add_time.desc()).paginate(page,
                                                                                                        per_page=5,
                                                                                                        error_out=False)
    posts = pagination.items
    return render_template('posts/index.html', posts=posts, pagination=pagination)


@posts.route('/single/<_id_>', methods=['GET', 'POST'])
def single(_id_):
    form = CommentForm()
    if form.validate_on_submit():
        comm = Comment(content=form.text.data, user_id=current_user.id, blog_id=_id_)
        blog = Blog.query.filter(Blog.id == _id_).first()
        blog.commentnum += 1
        db.session.add(blog)
        db.session.add(comm)
        return redirect(url_for('posts.single', _id_=_id_))
    post = Blog.query.filter(Blog.id == _id_).first()
    comments = Comment.query.filter(Comment.blog_id == _id_).all()
    return render_template('posts/single.html', post=post, form=form, comments=comments)


app/templates/posts/index.html
{# 每篇博客只有被点击查看才能评论 #}
{% from 'common/macro.html' import pagination_show %}
{% extends 'common/base.html' %}

{% block title %}
    我的博客
{% endblock %}

{% block page_content %}
    {% for post in posts %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static',filename='upload/'+post.user.icon) }}" alt="用户头像">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right">{{ moment(post.add_time).format('LLLL') }}</div>
                <h4 class="media-heading">{{ post.user.username }}</h4>
                {{ post.title }}
                <br>
{#                {{ post.text }}#}
                <a href="{{ url_for('posts.single', _id_=post.id) }}"> ...... </a>
            </div>
        </div>
    {% endfor %}
    <div align="center">
        {{ pagination_show(pagination,'posts.index') }}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/posts/search.html
{% extends 'common/base.html' %}
{% from 'common/macro.html' import pagination_show %}
{% block title %}
    搜索结果
{% endblock %}

{% block page_content %}
    {% for post in posts %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static',filename='upload/'+post.user.icon) }}" alt="用户头像">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right">{{ moment(post.add_time).format('LLLL') }}</div>
                <h4 class="media-heading">{{ post.user.username }}</h4>
                {{ post.title }}
                <br>
                {{ post.text }}
            </div>
        </div>
    {% endfor %}
    <div align="center">
        {{ pagination_show(pagination,'posts.index') }}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/posts/single.html
{% extends 'common/base.html' %}

{% block title %}
    博客
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/single.css') }}">
{% endblock %}

{% block page_content %}

    <div class="media">
        <div class="media-left media-middle">
            <a href="#">
                <img class="media-object" src="{{ url_for('static',filename='upload/'+post.user.icon) }}" alt="用户头像">
            </a>
        </div>
        <div class="media-body">
            <div style="float: right">{{ moment(post.add_time).format('LLLL') }}</div>
            <h4 class="media-heading">Author: {{ post.user.username }}</h4>


        </div>
    </div>
    <div class="media">
        <div class="div_1" align="center">
            Title: {{ post.title }}
        </div>

        <hr>
        <div class="div_2">
            Content: {{ post.text }}
        </div>
        评论：{{ post.commentnum }}条
        <hr>
    </div>
    {% if current_user.is_authenticated %}
        <button id="btn_col" class="btn btn-success">收藏</button>
        <div class="media">
            <font style="color:green" id="show_msg"></font>
        </div>
    {% endif %}
    {% for comment in comments %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static',filename='upload/'+comment.user.icon) }}"
                         alt="用户头像">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right">{{ moment(comment.add_time).format('LL') }}</div>
                <h4 class="media-heading">用户: {{ comment.user.username }}</h4>
                {{ comment.content }}
                <hr>
            </div>
        </div>
    {% endfor %}

    {% if current_user.is_authenticated %}
        {{ wtf.quick_form(form,form_type='horizontal',horizontal_columns=('lg',3,6)) }}
    {% endif %}

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(document).ready(function () {
            $("#btn_col").click(function () {
                bid = {{ post.id }};
                uid = {{ current_user.id }};
                $.ajax({
                    url: "{{ url_for('posts.collect') }}",
                    type: "GET",
                    data: "bid=" + bid + "&uid=" + uid,
                    datetype: "json",
                    success: function (res) {
                        if (res.ok == 1) {
                            $("#show_msg").empty();
                            $("#show_msg").append("收藏成功！");
                        } else {
                            $("#show_msg").empty();
                            $("#show_msg").append("取消收藏成功！");
                        }
                    }
                });

            });
        });
    </script>
{% endblock %}

app/templates/posts/write.html
{% extends 'common/base.html' %}

{% block title %}
    写博客
{% endblock %}

{% block page_content %}
        {{ wtf.quick_form(form, form_type='horizontal',horizontal_columns=('lg',3,6)) }}
{#    <form>#}
{#        {{ wtf.form_field(form.title) }}#}
{#        {{ wtf.form_field(form.text, height=200px)}}#}
{#        {{ wtf.form_field(form.submit) }}#}
{##}
{#    </form>#}
{% endblock %}